# Site
name: 'Tá tudo ok'
description: 'Documentando o desmonte da democracia no regime Bolsonaro.'
logo: ''
favicon: 'assets/images/favicon.ico'
baseurl: ''
avatar: ''
disqus: ''
email: ''

include: ["_pages"]
permalink: pretty
excerpt_separator: ""

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 500
paginate_path: "/pagina:num/"

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
